import type { Metadata } from "next";
import { anton, inter } from "@/data/fonts";
import "@/css/global.scss";
import { Footer, Navigation } from "@/layout/index";
import LayoutProvider from "@/context/LayoutContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <LayoutProvider>
        <body
          className={`${anton.variable} ${inter.variable}`}
          suppressHydrationWarning={true}
        >
          <Navigation />
          {children}
          <Footer />
        </body>
      </LayoutProvider>
    </html>
  );
}
