import type { Metadata } from "next";
import { anton, inter } from "@/data/fonts";
import "@/css/global.scss";
import { Footer } from "@/footer/index";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body
        className={`${anton.variable} ${inter.variable}`}
        suppressHydrationWarning={false}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
