import type { Metadata } from "next";
import {Mukta, Protest_Strike ,Source_Code_Pro} from "next/font/google";
import "../styles/Global.scss";
import {Footer} from "footer/index";
import { main } from "data/main";
import { MainProvider } from 'context/MainContext';
import { Navigation } from "nav/index";

const mukta = Mukta({ // REGURAL
  subsets:["latin-ext"],
  variable:"--mukta",
  weight:["200","300","400","500","600","700","800"]  
})

const protest = Protest_Strike({ // BOLD
  weight:["400"],
  subsets:["latin-ext"],
  variable:"--protest"
})

const source = Source_Code_Pro({ // CODE
  weight:["200","300","400","500","600","700","800"],
  subsets:["latin-ext"],
  variable:"--source"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <MainProvider>
        <body className={`${mukta.variable} ${protest.variable} ${source.variable}`}>
          <Navigation
            {...main.nav}
          />
          {children}
          <Footer
            {...main.footer}
          />
        </body>
      </MainProvider>
    </html>
  );
}
