import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "css/Global.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <head>
        <title>RadWEB</title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
