import type { Metadata } from "next";
import {Mukta, Righteous, Syne_Mono} from "next/font/google"
import "css/Global.scss"

const mukta = Mukta({
  weight:["300","400","500", "600","700"],
  subsets:["latin-ext","latin"],
  variable:"--mukta"
})

const righteous = Righteous({
  weight:["400"],
  subsets:["latin-ext","latin"],
  variable:"--righteous"
})

const syne_mono = Syne_Mono({
  weight:["400"],
  subsets:["latin-ext","latin"],
  variable:"--syne-mono"
})



export const metadata: Metadata = {
  title: "RadWEB - Layout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`${mukta.variable} ${righteous.variable} ${syne_mono.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
