export default async function Page() {
  return (
    <div>
      <ul>
        <li>Lorem.</li>
        <li>Rem?</li>
        <li>Natus.</li>
        <li>Necessitatibus!</li>
        <li>Quis.</li>
        <li>Exercitationem.</li>
        <li>Officiis?</li>
        <li>Vel.</li>
        <li>Ipsum?</li>
        <li>Error.</li>
        <li>Temporibus.</li>
        <li>Molestias.</li>
        <li>Excepturi!</li>
        <li>Mollitia?</li>
        <li>Dolore!</li>
        <li>Distinctio.</li>
        <li>Aut.</li>
        <li>Deserunt.</li>
        <li>Aperiam.</li>
        <li>Inventore.</li>
        <li>Dolores.</li>
        <li>Eos?</li>
        <li>Iste!</li>
        <li>Saepe.</li>
        <li>Laboriosam.</li>
        <li>Qui.</li>
        <li>Incidunt.</li>
        <li>Incidunt?</li>
        <li>Perferendis!</li>
        <li>Quidem.</li>
        <li>Cum!</li>
        <li>Nisi.</li>
        <li>Aliquid.</li>
        <li>Adipisci?</li>
        <li>Doloremque!</li>
        <li>Sequi.</li>
        <li>Vel!</li>
        <li>Expedita!</li>
        <li>Perspiciatis.</li>
        <li>Voluptas?</li>
        <li>Voluptatibus?</li>
        <li>Officia!</li>
        <li>Similique?</li>
        <li>Iste?</li>
        <li>Porro?</li>
        <li>Vero.</li>
        <li>Minima.</li>
        <li>Numquam!</li>
        <li>Non?</li>
        <li>Eaque.</li>
        <li>Quaerat?</li>
        <li>Rem!</li>
        <li>Facilis?</li>
        <li>Numquam.</li>
        <li>Deserunt.</li>
        <li>Accusamus.</li>
        <li>Quaerat!</li>
        <li>Illo?</li>
        <li>Aspernatur.</li>
        <li>Eum.</li>
        <li>Eaque.</li>
        <li>Eius!</li>
        <li>Repellendus!</li>
        <li>Commodi?</li>
        <li>Itaque.</li>
        <li>Quo?</li>
        <li>Quod?</li>
        <li>Incidunt?</li>
        <li>Eum?</li>
        <li>Repellendus.</li>
        <li>Sapiente.</li>
        <li>Alias?</li>
        <li>Mollitia.</li>
        <li>Accusantium!</li>
        <li>Consequatur?</li>
        <li>Illo!</li>
        <li>Quidem.</li>
        <li>Optio?</li>
        <li>Commodi.</li>
        <li>Quia.</li>
        <li>Autem.</li>
        <li>Odit.</li>
        <li>Dolorem!</li>
        <li>Repellendus!</li>
        <li>Corporis?</li>
        <li>Ex.</li>
        <li>Nam.</li>
        <li>Harum.</li>
        <li>Animi.</li>
        <li>Maiores?</li>
      </ul>
    </div>
  );
}
