import type { Metadata } from "next";
import "@/css/input.css";
import "@/css/global.css";
import { anton, inter } from "@/data/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${anton.variable} ${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
