import type { Metadata } from "next";
import { Roboto, Anton, Merienda, Alata, Source_Code_Pro} from "next/font/google";
import "css/Global.scss";

const alata = Alata({
  weight:["400"],
  subsets:["latin-ext"],
  variable:"--special"
})

const anton = Anton({
  subsets:["latin-ext"],
  weight:["400"],
  variable:"--heading"
})

const merienda = Merienda({
  weight:["300","400","500","700"],
  subsets:["latin-ext"],
  variable:"--cursive"
})

const sourceCode = Source_Code_Pro({
  subsets:["latin-ext"],
  weight:["400","700"],
  variable:"--code"
})

const roboto = Roboto({
  subsets:["latin-ext"],
  weight:["100","300","400","500","700","900"],
  variable:"--regular"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${alata.variable} ${anton.variable} ${merienda.variable} ${sourceCode.variable} ${roboto.variable}`}>{children}</body>
    </html>
  );
}
