import type { Metadata } from "next";
import { Roboto, Roboto_Condensed,Roboto_Mono, Roboto_Slab} from "next/font/google";
import "css/Global.scss";

const regular = Roboto({
  subsets:["latin-ext"],
  weight:["100","300","400","500","700","900"],
  variable:"--regular"
})

const mono = Roboto_Mono({
  subsets:["latin-ext"],
  weight:["100","200","300","400","500","600","700"],
  variable:"--mono"     
});

const bold = Roboto_Condensed({
  subsets:["latin-ext"],
  weight:["100","200","300","400","500","600","700","800","900"],
  variable:"--bold"
})

const serif = Roboto_Slab({
  subsets:["latin-ext"],
  weight:["100","200","300","400","500","600","700","800","900"],
  variable:"--serif"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body 
        className={`${bold.variable} ${mono.variable} ${regular.variable} ${serif.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
