import type { Metadata } from "next";
import { Lato, Roboto_Mono } from "next/font/google";
import "css/Global.scss";

const lato = Lato({
  weight:["100","300","400","700","900"],
  subsets:["latin-ext"],
  variable:"--regular"
})

const roboto = Roboto_Mono({
  weight:["200","400","600"],
  subsets:["latin-ext"],
  variable:"--mono"
})

export const metadata: Metadata = {
  title: "RadWEB - Marketing online: Web dev, SEO, SEM, Videomaking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl_PL">
      <body className={`${lato.variable} ${roboto.variable}`}>{children}</body>
    </html>
  );
}
