import type { Metadata } from "next";
import { Oswald, Nunito_Sans } from "next/font/google";
import "@/css/globals.scss";
// import { Navigation } from "@/nav/index";
import { MenuProvider } from "@/provider";

const oswald = Oswald({
  display: 'swap',
  subsets: ['latin-ext'],
  variable: '--font-oswald'
})

const nunito = Nunito_Sans({
  subsets: ['latin-ext'],
  display: 'swap',
  preload: true,
  variable: '--font-nunito'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl_PL">
      <MenuProvider>
        <body className={`${oswald.variable} ${nunito.variable}`}>
          {/* <Navigation /> */}
          {children}
        </body>
      </MenuProvider>
    </html>
  );
}
