import type { Metadata } from 'next';
import { Anton, Ubuntu } from 'next/font/google';
import './globals.css';

const anton = Anton({
	weight: ['400'],
	subsets: ['latin-ext', 'latin'],
	preload: true,
	variable: '--anton',
});

const ubuntu = Ubuntu({
	weight: ['300', '400', '500', '700'],
	preload: true,
	subsets: ['latin-ext', 'latin'],
	variable: '--ubuntu',
});

export const metadata: Metadata = {
	title: 'RadWEB - v16',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='pl'>
			<body className={`${anton.variable} ${ubuntu.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
