import type { Metadata } from "next";
import "css/Global.scss";
import { Alexandria } from "next/font/google"
import { Footer } from "layout/index";

const font = Alexandria({
  subsets:["latin-ext","latin"],
  preload:true,
  weight:["100","200","300","400","500","600","700","800","900"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body 
        className={font.className}
      >
        {children}
        <Footer
          author="RadWEB &copy; prawa zastrzezone" 
          company="RadWEB"
          email={{
            title:"radoslaw.adamczyk2000@gmail.com",
            url:"mailto:radoslaw.adamczyk2000@gmail.com"
          }}
          image={{
            altText:"",
            sourceUrl:"",
            title:""
          }}
          location="Dontatowo 53<br/>64-020 Czempiń"
          phone={{
            title:"+48 794-100-413",
            url:"tel:+48794100413"
          }}
          slogan="Współczesny marketing online"
          year={2021}
          menu={[
             {
              label:"RadWEB",
              items:[
                {
                  title:"Start",
                  url:"#"
                },
                {
                  title:"Blog",
                  url:"#"
                },
                {
                  title:"Projekty",
                  url:"#"
                },
                {
                  title:"Case study",
                  url:"#"
                },
                {
                  title:"Usługi",
                  url:"#"
                },
                {
                  title:"Słownik",
                  url:"#"
                },
                {
                  title:"FAQ",
                  url:"#"
                },
                {
                  title:"O nas",
                  url:"#"
                },
              ]
             },
             {
              label:"Blog",
              items:[
                {
                  title:"Programowanie",
                  url:"#"
                },
                {
                  title:"Pozycjonowanie",
                  url:"#"
                },
                {
                  title:"Google Ads",
                  url:"#"
                },
                {
                  title:"Social media",
                  url:"#"
                },
                {
                  title:"Copywriting",
                  url:"#"
                },
                {
                  title:"Videomaking",
                  url:"#"
                },
              ]
             },
             {
              label:"Usługi",
              items:[
                {
                  title:"Strony internetowe",
                  url:"#"
                },
                {
                  title:"SEO",
                  url:"#"
                },
                {
                  title:"SEM",
                  url:"#"
                },
                {
                  title:"Copywriting",
                  url:"#"
                },
                {
                  title:"Videomaking",
                  url:"#"
                },
                {
                  title:"Audyty",
                  url:"#"
                }
              ]
             },
             {
              label:"Informacje",
              items:[
                {
                  title:"Kontakt",
                  url:"#"
                },
                {
                  title:"Polityka prywatności",
                  url:"#"
                },
                {
                  title:"Polityka cookies",
                  url:"#"
                },
                {
                  title:"Referencje",
                  url:"#"
                }
              ]
             },
          ]}
          nip={{
            label:"NIP",
            content:12389012378
          }}
          socials={[
            "facebook.com",
            "linkedin.com",
            "instagram.com",
            "x.com",
            "youtube.com",
            "medium.com",
            "github.com",
          ]}
        />
      </body>
    </html>
  );
}
