import type { Metadata } from "next";
import "css/Global.scss";
import { Alexandria } from "next/font/google"
import { Footer } from "layout/index";
import {layout} from "data/layout"
const font = Alexandria({
  subsets:["latin-ext","latin"],
  preload:true,
  weight:["100","200","300","400","500","600","700","800","900"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body 
        className={font.className}
      >
        {children}
        <Footer
          {...layout.footer}
        />
      </body>
    </html>
  );
}
