export {default as AboutUs} from "v-home/AboutUs/AboutUs"
export {default as Hero} from "v-home/Hero/Hero"
export {default as Projects} from "v-home/Projects/Projects"
export {default as Services} from "v-home/Services/Services"
export {default as WhyUs} from "v-home/WhyUs/WhyUs"