import type { Metadata } from "next";
import "@/css/global.scss";
import "@/css/utils.scss";
import { TungstenBold } from "@/assets/fonts/fonts";
import { Navigation } from "@/nav/index";
import { main } from "@/data/main";
import MenuProvider from "@/context/MenuContext";
import { Footer } from "@/footer/index";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl" className={TungstenBold.variable}>
      <body>
        <MenuProvider>
          <Navigation {...main.nav} />
          {children}
          <Footer {...main.footer} />
        </MenuProvider>
      </body>
    </html>
  );
}
