import { About, Hero, Offer, Overview } from "@/v-home/index";
import { homePage } from "@/data/homePage";

export default function Home() {
  return (
    <div>
      <Hero {...homePage.hero} />
      <main>
        <Overview {...homePage.overview} />
        <About {...homePage.about} />
        <Offer {...homePage.offer} />
      </main>
      <ul>
        <li>Lorem.</li>
        <li>Minus.</li>
        <li>Nam!</li>
        <li>Sit.</li>
        <li>Quisquam.</li>
        <li>Excepturi.</li>
        <li>Delectus?</li>
        <li>Laboriosam?</li>
        <li>Voluptas?</li>
        <li>Expedita!</li>
        <li>Quas?</li>
        <li>Et.</li>
        <li>Facere.</li>
        <li>Cupiditate.</li>
        <li>Excepturi.</li>
        <li>Aliquam.</li>
        <li>Fuga?</li>
        <li>Natus.</li>
        <li>Inventore.</li>
        <li>Nam!</li>
        <li>Ea?</li>
        <li>Quis.</li>
        <li>Tempora.</li>
        <li>Quaerat!</li>
        <li>Facilis.</li>
        <li>Doloribus.</li>
        <li>Dolor?</li>
        <li>Esse!</li>
        <li>Placeat.</li>
        <li>Quam.</li>
        <li>Odio?</li>
        <li>Assumenda!</li>
        <li>Inventore!</li>
        <li>Et?</li>
        <li>Sint.</li>
        <li>Sequi?</li>
        <li>Quisquam.</li>
        <li>Unde.</li>
        <li>Voluptate.</li>
        <li>Ipsam!</li>
        <li>Fuga.</li>
        <li>Obcaecati.</li>
        <li>Amet!</li>
        <li>Vero.</li>
        <li>Consectetur!</li>
        <li>Nobis!</li>
        <li>Optio.</li>
        <li>Repellendus?</li>
        <li>Iusto.</li>
        <li>Animi.</li>
        <li>Suscipit?</li>
        <li>Expedita.</li>
        <li>Sunt.</li>
        <li>Iusto.</li>
        <li>Natus!</li>
        <li>Temporibus.</li>
        <li>Rerum.</li>
        <li>Nostrum?</li>
        <li>At!</li>
        <li>Cumque!</li>
        <li>Doloribus!</li>
        <li>Pariatur?</li>
        <li>Dolor.</li>
        <li>Repellat!</li>
        <li>Velit.</li>
        <li>A.</li>
        <li>Sed?</li>
        <li>Harum.</li>
        <li>Quas?</li>
        <li>Cupiditate.</li>
        <li>Autem!</li>
        <li>Nostrum?</li>
        <li>Dolorum.</li>
        <li>Reiciendis.</li>
        <li>Architecto.</li>
        <li>Ad.</li>
        <li>Laudantium.</li>
        <li>Odit.</li>
        <li>Ullam.</li>
        <li>Sint.</li>
        <li>Ut.</li>
        <li>Sed?</li>
        <li>Fugit.</li>
        <li>Pariatur.</li>
        <li>Nesciunt?</li>
        <li>Consequuntur?</li>
        <li>Ducimus.</li>
        <li>Tempore.</li>
        <li>Soluta.</li>
        <li>Eaque?</li>
        <li>Sit?</li>
        <li>Hic!</li>
        <li>Laboriosam!</li>
        <li>Quisquam!</li>
        <li>Dolorem!</li>
        <li>Laboriosam?</li>
        <li>Voluptatum.</li>
        <li>Blanditiis.</li>
        <li>Dolorum.</li>
        <li>Nobis!</li>
        <li>Sit.</li>
        <li>Placeat!</li>
        <li>Eaque.</li>
        <li>Provident.</li>
        <li>Quam!</li>
        <li>Fugiat?</li>
        <li>Natus.</li>
        <li>Accusantium!</li>
        <li>Tenetur!</li>
        <li>Tenetur?</li>
        <li>Quo.</li>
        <li>Et!</li>
        <li>Voluptate!</li>
        <li>Harum.</li>
        <li>Reiciendis!</li>
        <li>Quos.</li>
        <li>Fuga.</li>
        <li>Eius.</li>
        <li>Corporis.</li>
        <li>Temporibus.</li>
        <li>Voluptate!</li>
        <li>Laborum!</li>
        <li>Aliquid.</li>
      </ul>
    </div>
  );
}
