
import type { Metadata } from "next";
import {Spectral, Raleway} from "next/font/google"
import "css/Global.scss";
import { Navigation } from "nav/index";
import { MainProvider } from "context/MainContext";

const raleway = Raleway({
  subsets:["latin-ext"],
  preload:true,
  weight:["100","200","300","400","500","600","700","800","900"],
  variable:"--raleway"
})

const spectral = Spectral({
  weight:["600","700","800"],
  subsets:["latin-ext"],
  variable:"--spectral"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <MainProvider>
        <body className={`${raleway.variable} ${spectral.variable}`}>
          <Navigation/>
          {children}
        </body>
      </MainProvider>
    </html>
  );
}
